name: CI Workflow
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '19 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
      - run: pixi run scripts/main.py
      - run: git add .
      - run: git commit -m "Update data" || echo "No changes to commit"
      - run: git push
