name: Scrape
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 19 4-20 * * WED-FRI
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          cache: true
      - run: pixi run python3 scripts/main.py
      - run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - run: git add --all .
      - run: git status
      - run: git commit -m "Update data" || echo "No changes to commit"
      - run: git push
